[package]
name = "pqxdh_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
prost = "0.11"
hmac = "0.12"
sha2 = "0.10"
uuid = "1.3"
libsignal-protocol = { git = "https://github.com/signalapp/libsignal", branch = "main", package = "libsignal-protocol" }